### PR TITLE
add noarch label

### LINKED ISSUE #19: Convert recipe to noarch
I think this recipe could be converted to noarch, which would make it easier to support new architectures like arm64, aarch64, and ppc64le, and would also be faster to build (less packages).

### PR DESCRIPTION
**Pull request by mattip**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Make the package noarch, closes #19

This is the first time I have done this, I followed https://www.anaconda.com/blog/condas-new-noarch-packages

### CODE REVIEW

**Comment by mattip** [comment]
I used the proposed documentation in this PR conda-forge/conda-forge.github.io#1839 from @jaimergp, thanks!

**Comment by hadim** [comment]
Happy to merge once green.

Also feel free to add yourself as a maintainer of the package if you want.

**Comment by mattip** [comment]
I tried without a python version selector, which failed linting. I tried with `python >=3.7` but that [fails CI](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=593963&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=423)
> package python-3.7.10-0_73_pypy requires python_abi 3.7 *_pypy37_pp73, but none of the providers can be installed

Is there a way around that?

**Comment by mattip** [comment]
@conda-forge-admin, please rerender

**Comment by mattip** [comment]
trying to select for python >=3.8, since conda-forge will be dropping python ==3.7 in [after next week's 3.11 release](https://conda-forge.org/docs/user/announcements.html#dropping-python-3-7) anyway.

**Comment by mattip** [comment]
@hadim this is green, and will provide no-arch packages for python3.8 and over, meaning now aarch64, ppc64le, and macos arm64 support will be provided but only for python3.8+. The older 1.19.1 platform-specific packages will remain available for python3.7 and under.

**Comment by hadim** [comment]
Thanks.

**Pull request merged**
